# Generated by Django 3.1.7 on 2021-04-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0056_reviewscorecategory_is_independent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='require_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
