# Generated by Django 3.1.8 on 2021-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0057_question_require_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_required',
            field=models.CharField(default='none', max_length=13),
        ),
    ]
